# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: jmgoldsmith
  password: 123dfg123#
  host: myapp.cj3v7smthm1s.us-west-2.rds.amazonaws.com
  port: 5432 
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
